- src/main/java/com/example/server/admin/domain/controller/AdminController.java
- src/main/java/com/example/server/global/auth/security/handler/CustomAuthenticationEntryPoint.java
> test: 깃 브랜치 테스트

- src/main/java/com/example/server/domain/member/service/MemberService.java
- src/main/java/com/example/server/global/auth/security/dto/LoginResponseDto.java
- src/main/java/com/example/server/global/auth/security/handler/LoginSuccessJWTProvideHandler.java
> Feat/member/20 로그인 스펙 선 변경

- src/main/java/com/example/server/global/auth/security/handler/LoginSuccessJWTProvideHandler.java
- src/main/java/com/example/server/global/auth/security/service/JwtService.java
- src/main/java/com/example/server/global/auth/security/service/JwtServiceImpl.java
> feat: https환경일때 쿠키 전송하는 로직 구현

- src/main/java/com/example/server/global/config/SecurityConfig.java
> fix: cors 에러 수정 코드 적용

- src/main/java/com/example/server/domain/image/model/ImageType.java
- src/main/java/com/example/server/domain/image/repository/ImageRepository.java
- src/main/java/com/example/server/domain/post/controller/LikeController.java
- src/main/java/com/example/server/domain/post/controller/PostController.java
- src/main/java/com/example/server/domain/post/domain/Post.java
- src/main/java/com/example/server/domain/post/dto/PostDtoConverter.java
- src/main/java/com/example/server/domain/post/dto/PostRequestDto.java
- src/main/java/com/example/server/domain/post/dto/PostResponseDto.java
- src/main/java/com/example/server/domain/post/dto/TagResponseDto.java
- src/main/java/com/example/server/domain/post/service/PostService.java
- src/main/java/com/example/server/domain/ticket/controller/TicketController.java
- src/main/java/com/example/server/domain/ticket/domain/MemberTicket.java
- src/main/java/com/example/server/domain/ticket/domain/Ticket.java
- src/main/java/com/example/server/domain/ticket/dto/TicketDtoConverter.java
- src/main/java/com/example/server/domain/ticket/dto/TicketRequestDto.java
- src/main/java/com/example/server/domain/ticket/dto/TicketResponseDto.java
- src/main/java/com/example/server/domain/ticket/model/TicketColor.java
- src/main/java/com/example/server/domain/ticket/model/Transport.java
- src/main/java/com/example/server/domain/ticket/repository/TicketRepository.java
- src/main/java/com/example/server/domain/ticket/service/TicketService.java
- src/main/java/com/example/server/global/apiPayload/code/status/ErrorStatus.java
> feat/ticket: Ticket 기능 추가 및 그에 따른 게시물 수정

- src/main/java/com/example/server/domain/member/service/MemberService.java
- src/main/java/com/example/server/domain/notify/domain/Notify.java
- src/main/java/com/example/server/domain/notify/dto/NotifyDto.java
- src/main/java/com/example/server/domain/notify/dto/NotifyDtoConverter.java
- src/main/java/com/example/server/domain/notify/model/NotificationType.java
- src/main/java/com/example/server/domain/notify/repository/EmitterRepository.java
- src/main/java/com/example/server/domain/notify/repository/EmitterRepositoryImpl.java
- src/main/java/com/example/server/domain/notify/repository/NotifyRepository.java
- src/main/java/com/example/server/domain/notify/service/NotifyService.java
> fix: 팔로우 조회 안되는 버그 수정

- src/main/java/com/example/server/domain/member/controller/MemberController.java
실행결과 스크린샷 첨부
<br>
close #{이슈넘버}
<br>
<br>
<br>
> fix: 팔로워 조회 api 수정

- src/main/java/com/example/server/global/apiPayload/code/status/ErrorStatus.java
- src/main/java/com/example/server/global/auth/security/filter/SilentReAuthenticationFilter.java
실행결과 스크린샷 첨부
<br>
close #{이슈넘버}
<br>
<br>
<br>
> test: refreshToken 1분 테스트

- src/main/java/com/example/server/admin/domain/controller/AdminController.java
- src/main/java/com/example/server/domain/comment/service/CommentService.java
- src/main/java/com/example/server/domain/member/controller/MemberController.java
- src/main/java/com/example/server/domain/member/service/MemberService.java
- src/main/java/com/example/server/domain/notify/domain/NotifyMessageProvider.java
- src/main/java/com/example/server/domain/notify/dto/NotifyDtoConverter.java
- src/main/java/com/example/server/domain/notify/service/NotifyService.java
- src/main/java/com/example/server/domain/post/service/LikeService.java
실행결과 스크린샷 첨부
<br>
close #{이슈넘버}
<br>
<br>
<br>
> feat: 알림 기능 구현

- src/main/java/com/example/server/domain/member/controller/MemberController.java
- src/main/java/com/example/server/domain/member/dto/MemberDtoConverter.java
- src/main/java/com/example/server/domain/member/dto/MemberResponseDto.java
- src/main/java/com/example/server/global/config/SecurityConfig.java
실행결과 스크린샷 첨부
<br>
close #{이슈넘버}
<br>
<br>
<br>
> feat: 팔로워 조회 가능 여부 반환하는 기능 구현

- .github/workflows/gradle.yml
- .gitignore
- build.gradle
- src/main/java/com/example/server/admin/domain/controller/AdminController.java
- src/main/java/com/example/server/domain/member/service/MemberService.java
- src/main/java/com/example/server/domain/notify/controller/FCMTokenController.java
- src/main/java/com/example/server/domain/notify/controller/NotifyController.java
- src/main/java/com/example/server/domain/notify/domain/NotifyListener.java
- src/main/java/com/example/server/domain/notify/dto/FCMResponseDto.java
- src/main/java/com/example/server/domain/notify/dto/SaveFCMTokenRequestDto.java
- src/main/java/com/example/server/domain/notify/service/FCMNotifyService.java
- src/main/java/com/example/server/domain/notify/service/FCMTokenService.java
- src/main/java/com/example/server/domain/notify/service/NotifyService.java
- src/main/java/com/example/server/domain/notify/service/SseNotifyService.java
- src/main/java/com/example/server/global/apiPayload/code/status/ErrorStatus.java
- src/main/java/com/example/server/global/auth/security/handler/CustomAccessDeniedHandler.java
- src/main/java/com/example/server/global/config/AsyncConfig.java
- src/main/java/com/example/server/global/config/FcmConfig.java
- src/main/java/com/example/server/global/config/RedisConfig.java
- src/main/java/com/example/server/global/util/RedisUtil.java
> feat: FCM을 이용한 알림 기능 구현

- src/main/java/com/example/server/domain/image/controller/ImageController.java
- src/main/java/com/example/server/domain/image/service/ImageService.java
- src/main/java/com/example/server/domain/image/service/OracleImageService.java
- src/main/java/com/example/server/domain/member/domain/Member.java
- src/main/java/com/example/server/domain/member/service/MemberService.java
- src/main/java/com/example/server/global/apiPayload/code/status/ErrorStatus.java
- src/main/java/com/example/server/global/config/FcmConfig.java
실행결과 스크린샷 첨부
<br>
close #106 
<br>
<br>
<br>
> feat: 사진 업로드 제한횟수 적용 기능구현

- src/main/java/com/example/server/domain/notify/domain/NotifyListener.java
- src/main/java/com/example/server/domain/notify/service/FCMTokenService.java
- src/main/java/com/example/server/global/auth/security/handler/CustomAccessDeniedHandler.java
- src/main/java/com/example/server/global/config/SecurityConfig.java
실행결과 스크린샷 첨부
<br>
close #{이슈넘버}
<br>
<br>
<br>
> fix: fcm 키 없으면 요청 보내지 않도록 로직 변경

- src/main/java/com/example/server/global/auth/security/handler/CustomAuthenticationEntryPoint.java
실행결과 스크린샷 첨부
<br>
close #{이슈넘버}
<br>
<br>
<br>
> fix : 에러 핸들러에 커밋시 동작하지 않도록 수정

- src/main/java/com/example/server/domain/comment/domain/Comment.java
- src/main/java/com/example/server/domain/comment/service/CommentService.java
- src/main/java/com/example/server/domain/member/controller/MemberController.java
- src/main/java/com/example/server/domain/member/domain/Member.java
- src/main/java/com/example/server/domain/member/dto/MemberRequestDto.java
- src/main/java/com/example/server/domain/member/service/MemberService.java
- src/main/java/com/example/server/domain/notify/service/FCMTokenService.java
- src/main/java/com/example/server/domain/post/domain/Post.java
- src/main/java/com/example/server/global/apiPayload/code/status/ErrorStatus.java
- src/main/java/com/example/server/global/auth/oauth2/model/SocialType.java
- src/main/java/com/example/server/global/auth/oauth2/model/socialLoader/GoogleLoadStrategy.java
- src/main/java/com/example/server/global/auth/oauth2/model/socialLoader/KakaoLoadStrategy.java
- src/main/java/com/example/server/global/auth/oauth2/model/socialLoader/NaverLoadStrategy.java
- src/main/java/com/example/server/global/auth/oauth2/model/socialLoader/SocialLoadStrategy.java
- src/main/java/com/example/server/global/auth/security/domain/JwtTokenProvider.java
- src/main/java/com/example/server/global/auth/security/filter/JwtAuthenticationFilter.java
- src/main/java/com/example/server/global/auth/security/handler/LoginSuccessJWTProvideHandler.java
- src/main/java/com/example/server/global/auth/security/handler/LogoutHandlerImpl.java
- src/main/java/com/example/server/global/auth/security/handler/LogoutSuccessHandler.java
- src/main/java/com/example/server/global/auth/security/service/JwtService.java
- src/main/java/com/example/server/global/auth/security/service/JwtServiceImpl.java
- src/main/java/com/example/server/global/config/SecurityConfig.java
- src/main/java/com/example/server/global/util/DeviceUtil.java
- src/main/java/com/example/server/global/util/RedisUtil.java
> 회원 탈퇴 & 로그아웃 로직 구현

- src/main/java/com/example/server/domain/comment/service/CommentService.java
실행결과 스크린샷 첨부
<br>
close #{이슈넘버}
<br>
<br>
<br>
> refactor: 글자길이 30자 제한 해제

- src/main/java/com/example/server/domain/comment/domain/Comment.java
- src/main/java/com/example/server/domain/comment/dto/CommentDtoConverter.java
- src/main/java/com/example/server/domain/comment/dto/CommentRequestDto.java
- src/main/java/com/example/server/domain/comment/dto/CommentResponseDto.java
- src/main/java/com/example/server/domain/comment/repository/CommentRepository.java
- src/main/java/com/example/server/domain/comment/service/CommentService.java
- src/main/java/com/example/server/global/apiPayload/code/status/ErrorStatus.java
실행결과 스크린샷 첨부
<br>
close #122
<br>
<br>
<br>
> refactor: 댓글과 대댓글 구현 방식 수정

- src/main/java/com/example/server/domain/member/repository/MemberRepository.java
- src/main/java/com/example/server/domain/search/controller/SearchController.java
- src/main/java/com/example/server/domain/search/dto/SearchDtoConverter.java
- src/main/java/com/example/server/domain/search/dto/SearchResponseDto.java
- src/main/java/com/example/server/domain/search/model/SearchType.java
- src/main/java/com/example/server/domain/search/service/SearchService.java
실행결과 스크린샷 첨부
<br>
close #{이슈넘버}
<br>
<br>
<br>
> feat: 닉네임, 블로그 검색

- src/main/java/com/example/server/domain/search/controller/SearchController.java
- src/main/java/com/example/server/domain/search/dto/SearchRequestDto.java
- src/main/java/com/example/server/domain/search/model/SearchType.java
- src/main/java/com/example/server/domain/search/service/SearchService.java
실행결과 스크린샷 첨부
<br>
close #{이슈넘버}
<br>
<br>
<br>
> fix: 검색 로직 수정

- src/main/java/com/example/server/domain/member/controller/MemberController.java
- src/main/java/com/example/server/domain/member/dto/MemberDtoConverter.java
- src/main/java/com/example/server/domain/member/dto/MemberResponseDto.java
- src/main/java/com/example/server/domain/member/model/InterestedType.java
- src/main/java/com/example/server/domain/member/service/MemberService.java
- src/main/java/com/example/server/domain/post/controller/PostController.java
- src/main/java/com/example/server/domain/post/dto/PostDtoConverter.java
- src/main/java/com/example/server/domain/post/dto/PostResponseDto.java
- src/main/java/com/example/server/domain/post/service/PostService.java
- src/main/java/com/example/server/domain/recommend/controller/RecommendController.java
- src/main/java/com/example/server/domain/recommend/service/RecommendService.java
- src/main/java/com/example/server/global/apiPayload/code/status/ErrorStatus.java
- src/main/java/com/example/server/global/config/SecurityConfig.java
실행결과 스크린샷 첨부
<br>
close #{이슈넘버}
<br>
<br>
<br>
> 추천 게시물 반환 기능 구현

- src/main/java/com/example/server/domain/recommend/dto/RecommendResponseDto.java
- src/main/java/com/example/server/domain/recommend/service/RecommendService.java
실행결과 스크린샷 첨부
<br>
close #{이슈넘버}
<br>
<br>
<br>
> feat: 카카오 이미지 검색 기능 구현

- src/main/java/com/example/server/domain/member/domain/Member.java
- src/main/java/com/example/server/domain/member/repository/MemberRepository.java
- src/main/java/com/example/server/domain/member/service/MemberService.java
- src/main/java/com/example/server/global/auth/security/filter/JwtAuthenticationFilter.java
실행결과 스크린샷 첨부
<br>
close #{이슈넘버}
<br>
<br>
<br>
> fix: member에 like 종속성 안해준 오류 수정
